# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('dinner', 'обед'), ('breakfast', 'завтрак'), ('supper', 'ужин')], max_length=1)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('text', models.TextField(verbose_name='Описание')),
                ('calories', models.BigIntegerField(blank=True, null=True, verbose_name='калории')),
                ('price', models.BigIntegerField(error_messages={'required': 'Determine the price'}, null=True, verbose_name='цена')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.FileField(null=True, upload_to='images/dishes', verbose_name='изображение блюда')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('First', 'Первое'), ('Second', 'Гарнир'), ('Third', 'Второе'), ('Self', 'Самостоятельное'), ('Salad', 'Салат'), ('Baverage', 'Напиток')], max_length=50, verbose_name='Тип ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(to='blog.Ingredient', verbose_name='список продуктов')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
