# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kkal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.BigIntegerField(error_messages={'required': 'Укажите цену'}, null=True),
        ),
    ]
