# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160527_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='images/dishes'),
        ),
    ]
