# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160527_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='kkal',
            new_name='calories',
        ),
    ]
