# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160528_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('weight', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('included_to', models.ManyToManyField(blank=True, null=True, related_name='ingredients', to='blog.Post')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
