# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='included_to',
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='blog.Ingredient'),
        ),
    ]
