# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160601_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(to='blog.Ingredient'),
        ),
    ]
