# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160602_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.BigIntegerField(error_messages={'required': 'Determine the priceyi'}, null=True),
        ),
    ]
