# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20160609_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
